name: forcechallenge
description: A force challenge Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  built_value: ^7.0.9
  dio: ^3.0.9
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.5

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  mobx_codegen: ^1.0.3
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/yoda_baby.png

